config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
 
  scope :consumer do
    get 'products', to: 'admin#index'
    resources :users, only: [:index]  
    post 'admin', to: 'users#admin'
    resources :accessories
    resources :essences
    resources :vapes
  end

  scope :store do
    get 'cart', to: 'cart#show'
    resources :orders
  resources :order_items
  end

end

app/models/accessory.rb
class Accessory < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
   
  validates_uniqueness_of :name

  belongs_to :order_item, foreign_key: 'code', primary_key: 'code', optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/essence.rb
class Essence < ApplicationRecord
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :quantity, presence: true,numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :flavor, presence: true
  validates :size, presence: true, numericality: { greater_than_or_equal_to: 0 }
    
  validates_uniqueness_of :name
  enum strength: { soft: 0, medium: 1, hard: 2 }

  belongs_to :order_item , foreign_key: 'code', primary_key: 'code', optional: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_save :set_subtotal

  validates :status , presence:  true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.price * order_item.quantity : 0 }.sum
  end

  public

  def set_subtotal
    self[:amount] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  has_one :vape, foreign_key: 'code', primary_key: 'code'
  has_one :essence, foreign_key: 'code', primary_key: 'code'
  has_one :accessory, foreign_key: 'code', primary_key: 'code'
 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase }
  has_many :orders, dependent: :destroy
  validates :username , presence: true, length: {minimum:3, maximum:30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence:  true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX}
  
end

app/models/vape.rb
class Vape < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :warrancy, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
   
  validates_uniqueness_of :name

  belongs_to :order_item, foreign_key: 'code', primary_key: 'code', optional: true
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  # GET /users or /users.json
  def index
    @vapers = Vape.paginate(page: params[:page], per_page: 5)
    @essences = Essence.paginate(page: params[:page], per_page: 5)
    @accessories = Accessory.paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html
      format.json { render :json => { :accessories => @accessories, 
                                      :essences => @essences, 
                                      :vapers => @vapers 
                                     }
                  }
    end
  end

  private
    
    def require_admin
      if !current_user.admin?
        redirect_to root_path  
      end
    end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items.paginate(page: params[:page], per_page: 10)
    @order = current_order
    
    respond_to do |format|
      format.html
      format.json { render :json => { :order => @order, 
                                      :order_items => @order_items
                                     }
                  }
    end
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]
  
  def home
    query = "quantity > ?", 0
    query = "quantity > ? and name LIKE ?", 0 ,"%#{params[:search][:search]}%" if params[:search]
    @products = Vape.where(query) + Essence.where(query) + Accessory.where(query)
    @products = @products.sort_by{ |h| h[:updated_at] }.reverse
    @products = @products.paginate(:page => params[:page], :per_page => 8) 
    
    respond_to do |format|
      format.html
      format.json { render :json => { :products => @products } }
    end
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/essence_helper.rb
module EssenceHelper
end

app/helpers/liquids_helper.rb
module LiquidsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vape_helper.rb
module VapeHelper
end

app/views/cart/show.html.erb
<section class="py-5">
  <div class="container">
    <% if @order_items.empty? %>
      <div class="card">
        <article class="card-body mx-auto" style="max-width: 400px;">
          <h4 class="card-title mt-3 mb-3 text-center">Your cart is empty</h4>
        </article>
      </div>
      <%= link_to 'Back', root_path, class: "btn btn-outline-dark mt-3 mb-3" %>
    <% else %>
      <div class="card apple_pagination">
        <div class="row px-3">
          <h4 class="card-title mt-3 mb-3 text-center col-8">MY CART</h4>
          <h4 class="card-title mt-3 mb-3 text-center col-4">Total : <%= number_to_currency(@order.amount) %></h4>
        </div>
        <table class="table col-10">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Brand</th>
              <th scope="col">Price</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @order_items.each do |item| %>
              <tr>
                <% if item.vape %>
                  <td><%= item.vape.name %></td>
                  <td><%= item.vape.brand %></td>
                  <td><%= number_to_currency(item.vape.price) %></td>  
                <% end %>
                <% if item.essence %>
                  <td><%= item.essence.name %></td>
                  <td><%= item.essence.brand %></td>
                  <td><%= number_to_currency(item.essence.price) %></td>  
                <% end %>
                <% if item.accessory %>
                  <td><%= item.accessory.name %></td>
                  <td><%= item.accessory.brand %></td>
                  <td><%= number_to_currency(item.accessory.price) %></td>  
                <% end %>
                <td>
                  <%= button_to "Remove from Cart", order_item_path(item), method: :delete,  class: "btn btn-danger", data: { confirm: 'Are you sure?' }  %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @order_items %>
      </div>
      <%= form_with(model: @order, local: true) do |f| %>
        <%= f.hidden_field :status, value: "Processing" %>
        <%= f.submit "Buy Now",class: "btn btn-primary block mt-2", id: "buy_now" %>  
      <% end %>
    <% end %>  
  </div>
</section>