config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
 
  scope :consumer do
    get 'products', to: 'admin#index'
    resources :users, only: [:index]  
    post 'admin', to: 'users#admin'
    resources :accessories
    resources :essences
    resources :vapes
  end

  scope :store do
    get 'cart', to: 'cart#show'
    resources :orders
  resources :order_items
  end

end

app/models/accessory.rb
class Accessory < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
   
  validates_uniqueness_of :name

  belongs_to :order_item, foreign_key: 'code', primary_key: 'code', optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/essence.rb
class Essence < ApplicationRecord
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :quantity, presence: true,numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :flavor, presence: true
  validates :size, presence: true, numericality: { greater_than_or_equal_to: 0 }
    
  validates_uniqueness_of :name
  enum strength: { soft: 0, medium: 1, hard: 2 }

  belongs_to :order_item , foreign_key: 'code', primary_key: 'code', optional: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_save :set_subtotal

  validates :status , presence:  true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.price * order_item.quantity : 0 }.sum
  end

  public

  def set_subtotal
    self[:amount] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  has_one :vape, foreign_key: 'code', primary_key: 'code'
  has_one :essence, foreign_key: 'code', primary_key: 'code'
  has_one :accessory, foreign_key: 'code', primary_key: 'code'
 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase }
  has_many :orders, dependent: :destroy
  validates :username , presence: true, length: {minimum:3, maximum:30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence:  true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX}
  
end

app/models/vape.rb
class Vape < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :warrancy, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
   
  validates_uniqueness_of :name

  belongs_to :order_item, foreign_key: 'code', primary_key: 'code', optional: true
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items.paginate(page: params[:page], per_page: 10)
    @order = current_order
    
    respond_to do |format|
      format.html
      format.json { render :json => { :order => @order, 
                                      :order_items => @order_items
                                     }
                  }
    end
    
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/essence_helper.rb
module EssenceHelper
end

app/helpers/liquids_helper.rb
module LiquidsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vape_helper.rb
module VapeHelper
end

app/views/admin/index.html.erb
<section class="py-5">
  <div class="container">
    <div class="card apple_pagination">
      <div class="row px-3">
        <%= link_to 'New Vape', new_vape_path, class: "btn btn-dark mt-3 mb-3 mx-auto col-2" %>
        <h4 class="card-title mt-3 mb-3 text-center col-10">VAPERS LIST</h4>
      </div>
      <table class="table col-10">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Brand</th>
            <th scope="col">Price</th>
            <th scope="col">Available</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @vapers.each do |vape| %>
            <tr>
              <td><%= vape.name %></td>
              <td><%= vape.brand %></td>
              <td><%= number_to_currency(vape.price) %></td>
              <td><%= vape.quantity %></td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <%= link_to 'Details', vape, class:"btn btn-secondary" %>
                  <%= link_to 'Edit', edit_vape_path(vape), class:"btn btn-secondary" %>
                  <%= button_to "Destroy", vape_path(vape), method: :delete,  class: "btn btn-secondary", data: { confirm: 'Are you sure?' }  %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @vapers %>
    </div> 
  </div>

  <div class="container">
    <div class="card apple_pagination">
      <div class="row px-3">
        <%= link_to 'New Essence', new_essence_path, class: "btn btn-dark mt-3 mb-3 mx-auto col-2" %>
        <h4 class="card-title mt-3 mb-3 text-center col-10">ESSENCE LIST</h4>
      </div>
      <table class="table col-10">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Brand</th>
            <th scope="col">Price</th>
            <th scope="col">Available</th>
            <th scope="col" colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @essences.each do |essence| %>
            <tr>
              <td><%= essence.name %></td>
              <td><%= essence.brand %></td>
              <td><%= number_to_currency(essence.price) %></td>
              <td><%= essence.quantity %></td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <%= link_to 'Details', essence, class:"btn btn-secondary" %>
                  <%= link_to 'Edit', edit_essence_path(essence), class:"btn btn-secondary" %>
                  <%= button_to "Destroy", essence_path(essence), method: :delete,  class: "btn btn-secondary", data: { confirm: 'Are you sure?' }  %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @essences %>
    </div> 
  </div>

  <div class="container">
    <div class="card apple_pagination">
      <div class="row px-3">
        <%= link_to 'New Accessory', new_accessory_path, class: "btn btn-dark mt-3 mb-3 mx-auto col-2" %>
        <h4 class="card-title mt-3 mb-3 text-center col-10">ACCESSORIES LIST</h4>
      </div>
      <table class="table col-10">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Brand</th>
            <th scope="col">Price</th>
            <th scope="col">Available</th>
            <th scope="col" colspan="4">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @accessories.each do |accessory| %>
            <tr>
              <td><%= accessory.name %></td>
              <td><%= accessory.brand %></td>
              <td><%= number_to_currency(accessory.price) %></td>
              <td><%= accessory.quantity %></td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <%= link_to 'Details', accessory, class:"btn btn-secondary" %>
                  <%= link_to 'Edit', edit_accessory_path(accessory), class:"btn btn-secondary" %>
                  <%= button_to "Destroy", accessory_path(accessory), method: :delete,  class: "btn btn-secondary", data: { confirm: 'Are you sure?' }  %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @accessories %>
    </div> 
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 bg-dark text-white">
  <div class="container text-center">
    <small>Made with love and coffee by <%= link_to "João Henrique Bitencourt Loli", "https://bairesdev.com", class: "text-white" %>.</small>
  </div>
</footer> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-4 px-lg-5">
    <%= link_to root_path do %>
      <%= image_tag "bairesdev.png", class: "navbar-brand" %>
    <% end %>
    <div class="navbar " id="navbarSupportedContent">
      <%# <% if current_page?(:controller => 'pages', :action => 'home') %> %>
        <%= form_for("search", url: root_path, method: :get ) do |f| %>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>      
              </span>
            </div>
            <%= f.text_field :search, class: "form-control", placeholder: "Search" %>
          </div>
        <% end %>
      <%# <% end %> %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin 
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Users', users_path, class: "dropdown-item"%>
                <div class="dropdown-divider"></div>
                <%= link_to 'Products', products_path, class: "dropdown-item"%>
                <div class="dropdown-divider"></div>
                <%= link_to 'API', "/api-docs", class: "dropdown-item", target: "_blank"%>
              </div>
            </li>
          <% end %>             
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Welcome <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit Profile', edit_user_registration_url(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Orders', orders_url, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
          </li>
          <li class="nav-item"><%= link_to "Cart", cart_url, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_url, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Log In", new_user_session_url, class: "nav-link" %></li>
        <% end %> 
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="container mt-5">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store - João Bitencourt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin: 0" class ="image-bg">
    <%= render 'layouts/header' %>
    <div id="page-content" >
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_items.html.erb
<% @products.each do |product| %>
  <div class="col mb-5">
    <div class="card h-100">
      <img class="card-img-top" src="https://picsum.photos/450/300?random=<%= product.id %>" >
      <div class="card-body p-4">
        <div class="text-center">
          <h5 class="fw-bolder"><%= product.name %></h5>
          <p class="fw-bolder"><%= product.brand %></p>
          <%= number_to_currency(product.price) %>
        </div>
      </div>
      <!-- Product actions-->
      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
        <div class="text-center">
        <%= form_with scope: :order_item, url: order_items_path do |f| %>
          <%= f.hidden_field :code, value: product.code %>
          <%= f.hidden_field :price, value: product.price %>
          <%= f.hidden_field :quantity, value: "1" %>
          <%= f.submit "ADD TO CART", class: "btn btn-outline-dark mt-auto" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<section class="py-5">
  <div class="container px-4 px-lg-5 apple_pagination">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <%= render 'items' %>
    </div>
    <%= will_paginate @products %>
  </div>
</section>