config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
 
  scope :consumer do
    get 'products', to: 'admin#index'
    resources :users, only: [:index]  
    post 'admin', to: 'users#admin'
    resources :accessories
    resources :essences
    resources :vapes
  end

  scope :store do
    get 'cart', to: 'cart#show'
    resources :orders
  resources :order_items
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase }
  has_many :orders, dependent: :destroy
  validates :username , presence: true, length: {minimum:3, maximum:30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence:  true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX}
  
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new]
  before_action :require_admin, only: %i[ index ]


  # GET /users or /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html
      format.json { render :json => { :users => @users } }
    end

  end

  def admin
    @user = User.find(params[:format])
    @user.toggle(:admin)

    respond_to do |format|
      if @user.save 
        format.html do
          redirect_to '/'
        end
        format.json { render json: @user.to_json }
      else
        format.html { render 'new'} ## Specify the format in which you are rendering "new" page
        format.json { render json: @reservation.errors } ## You might want to specify a json format as well
      end
    end
  end

  # GET /users/1 or /users/1.json
  def show
  end

    
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<section class="py-5">
  <div class="container">
    <div class="card apple_pagination">
      <div class="row px-3">
        <h4 class="card-title mt-3 mb-3 text-center col-10">USERS LIST</h4>
      </div>
      <table class="table col-10">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <% if user.admin? %>
                    <%= link_to 'Remove Admin', admin_path(user), class:"btn btn-secondary" , method: :post, data: { confirm: 'Are you sure?' } %>
                  <% else %>                  
                    <%= link_to 'Make Admin', admin_path(user), class:"btn btn-secondary", method: :post, data: { confirm: 'Are you sure?' }  %>
                  <% end %>
                  
                  <%= link_to 'Edit', edit_user_registration_url(user), class:"btn btn-secondary" if user.id == current_user.id %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @users %>
    </div> 
  </div>
</section>

app/views/users/show.html.erb
<section class="py-5">
    <div class="container">

      <div class="card">
        <article class="card-body mx-auto" style="max-width: 70%;">
          
            <div class="form-group input-group mb-3">
              <h5><strong>Name:</strong> <%= @user.username %></h5>
            </div>
            <div class="form-group input-group mb-3">
              <h5><strong>Email:</strong> <%= @user.email %></h5>
            </div>                               

        </article>
      </div> <!-- card.// -->
      <%= link_to 'Back', users_path, class: "btn btn-outline-dark btn-block mt-3 mb-3" %>
      <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-outline-dark btn-block mt-3 mb-3" %>
  </div>
</section>