config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
 
  scope :consumer do
    get 'products', to: 'admin#index'
    resources :users, only: [:index]  
    post 'admin', to: 'users#admin'
    resources :accessories
    resources :essences
    resources :vapes
  end

  scope :store do
    get 'cart', to: 'cart#show'
    resources :orders
  resources :order_items
  end

end

app/models/accessory.rb
class Accessory < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
   
  validates_uniqueness_of :name

  belongs_to :order_item, foreign_key: 'code', primary_key: 'code', optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/essence.rb
class Essence < ApplicationRecord
  
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :quantity, presence: true,numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :flavor, presence: true
  validates :size, presence: true, numericality: { greater_than_or_equal_to: 0 }
    
  validates_uniqueness_of :name
  enum strength: { soft: 0, medium: 1, hard: 2 }

  belongs_to :order_item , foreign_key: 'code', primary_key: 'code', optional: true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items
  before_save :set_subtotal

  validates :status , presence:  true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.price * order_item.quantity : 0 }.sum
  end

  public

  def set_subtotal
    self[:amount] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  has_one :vape, foreign_key: 'code', primary_key: 'code'
  has_one :essence, foreign_key: 'code', primary_key: 'code'
  has_one :accessory, foreign_key: 'code', primary_key: 'code'
 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save { self.email = email.downcase }
  has_many :orders, dependent: :destroy
  validates :username , presence: true, length: {minimum:3, maximum:30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence:  true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX}
  
end

app/models/vape.rb
class Vape < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :brand, presence: true
  validates :warrancy, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
   
  validates_uniqueness_of :name

  belongs_to :order_item, foreign_key: 'code', primary_key: 'code', optional: true
  
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: %i[ show edit update destroy ]

  # GET /accessories or /accessories.json
  def index
    @accessories = Accessory.all
    
    respond_to do |format|
      format.html
      format.json { render json: @accessories }
    end
  end

   # GET /accessories/1 or /accessories/1.json
   def show
    @accessory = Accessory.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render :json => { :accessory => @accessory } }
    end
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories or /accessories.json
  def create
    @accessory = Accessory.new(accessory_params.merge(:code => Time.now.to_i))

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to products_path, notice: "Accessory was successfully created." }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1 or /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to products_path, notice: "Accessory was successfully updated." }
        format.json { render :show, status: :ok, location: @accessory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1 or /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: "Accessory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accessory_params
      params.require(:accessory).permit(:name, :brand, :price, :quantity )
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

  # GET /users or /users.json
  def index
    @vapers = Vape.paginate(page: params[:page], per_page: 5)
    @essences = Essence.paginate(page: params[:page], per_page: 5)
    @accessories = Accessory.paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html
      format.json { render :json => { :accessories => @accessories, 
                                      :essences => @essences, 
                                      :vapers => @vapers 
                                     }
                  }
    end
  end

  private
    
    def require_admin
      if !current_user.admin?
        redirect_to root_path  
      end
    end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items.paginate(page: params[:page], per_page: 10)
    @order = current_order
    
    respond_to do |format|
      format.html
      format.json { render :json => { :order => @order, 
                                      :order_items => @order_items
                                     }
                  }
    end
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home]
  
  def home
    query = "quantity > ?", 0
    query = "quantity > ? and name LIKE ?", 0 ,"%#{params[:search][:search]}%" if params[:search]
    @products = Vape.where(query) + Essence.where(query) + Accessory.where(query)
    @products = @products.sort_by{ |h| h[:updated_at] }.reverse
    @products = @products.paginate(:page => params[:page], :per_page => 8) 
    
    respond_to do |format|
      format.html
      format.json { render :json => { :products => @products } }
    end
  end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/essence_helper.rb
module EssenceHelper
end

app/helpers/liquids_helper.rb
module LiquidsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vape_helper.rb
module VapeHelper
end

app/views/accessories/_form.html.erb
<%= form_with(model: @accessory, local: true) do |f| %>
  <div class="form-group input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Name</span>
    </div>
    <%= f.text_field :name, class: "form-control", placeholder: "Product Name" %>
  </div>              
  <div class="form-group input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Brand</span>
    </div>
    <%= f.text_field :brand, class: "form-control", placeholder: "Product Brand" %>
  </div>  
  <div class="form-group input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Price </span>
    </div>
    <%= f.number_field :price, class: "form-control", placeholder: "Price $", step: 0.01, min: 0 %>
  </div> 
  <div class="form-group input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">Quantity</span>
    </div>
    <%= f.number_field :quantity, class: "form-control", placeholder: "Quantity", min: 1, max: 999 %>
  </div>                          
  <div class="form-group text-center mb-3">
      <%= f.submit  class: "btn btn-primary btn-block" %>
  </div> <!-- form-group// -->                                                               
<% end %>

app/views/accessories/edit.html.erb
<section class="py-5">
  <div class="container">
    <div class="card">
      <article class="card-body mx-auto">
        <h4 class="card-title mt-3 mb-3 text-center">NEW ACCESSORY</h4>
        <%= render 'form' %>
      </article>
    </div> <!-- card.// -->
    <%= link_to 'Back', products_path, class: "btn btn-outline-primary mt-3 mb-3" %>
  </div>
</section>

app/views/accessories/new.html.erb
<section class="py-5">
  <div class="container">
    <div class="card">
      <article class="card-body mx-auto">
        <h4 class="card-title mt-3 mb-3 text-center">NEW ACCESSORY</h4>
        <%= render 'form' %>
      </article>
    </div> <!-- card.// -->
    <%= link_to 'Back', products_path, class: "btn btn-outline-primary mt-3 mb-3" %>
  </div>
</section>

app/views/accessories/show.html.erb
<h1><%= @accessory.name %></h1>
<h4>Price :<%= @accessory.price %></h4>
<h4>Brand : <%= @accessory.brand %></h4>



<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>